#ifndef __OUTPUT_REDIS_ICS_H
#define __OUTPUT_REDIS_ICS_H

#define MODULE_NAME	"ICSRadisLog"
#define REDIS_SERVER_IP	"127.0.0.1"
#define REDIS_SERVER_PORT	6379
#define REDIS_PUBLISH_CMD	"PUBLISH"
#define ICS_AUDIT_CHANNEL	"ChannelICSAudit"
#define ICS_STUDY_CHANNEL	"ChannelICSStudy"
#define ICS_WARN_CHANNEL	"ChannelICSWarn"
#define ICS_AUDIT_DATA_BUF_MAX	256
#define ICS_STUDY_DATA_BUF_MAX	256
#define ICS_WARN_DATA_BUF_MAX	512

typedef enum {
	BEGIN = 1,
	TEMPLATE_ID,
	SRC_MAC,
	DST_MAC,
	SRC_IPv4,
	DST_IPv4,
	SRC_PORT,
	DST_PORT,
	PROTO,
	FLOW_HASH,
	PKTLEN,
	PAYLOAD_LEN,
	APP_PROTO,
	MODBUS_FUNCODE,
	MODBUS_RADDR,
	MODBUS_RQUANTITY,
	MODBUS_WADDR,
	MODBUS_WQUANTITY,
	MODBUS_SUBFUNC,
	MODBUS_AND_MASK,
	MODBUS_OR_MASK,
	MODBUS_DATA_LEN,
	MODBUS_DATA,
	DNP3_FUNCODE,
	DNP3_GROUP,
	DNP3_VARIATION,
	DNP3_INDEX,
	DNP3_SIZE,
	DNP3_OBJECT_COUNTS,
	DNP3_OBJECTS,
	TRDP_PACKET_TYPE,
	TRDP_PACKET_HEADER,
	TRDP_PACKET_DATA,
	TRDP_WARNING_DATA,
	END,
} ics_tlv_type_t;

void ICSRedisLogRegister(void);
#endif
