#ifndef __OUTPUT_REDIS_ICS_H
#define __OUTPUT_REDIS_ICS_H

#define MODULE_NAME	"ICSRadisLog"
#define REDIS_SERVER_IP	"127.0.0.1"
#define REDIS_SERVER_PORT	6379
#define REDIS_PUBLISH_CMD	"PUBLISH"
#define ICS_AUDIT_CHANNEL	"ChannelICSAudit"
#define ICS_STUDY_CHANNEL	"ChannelICSStudy"
#define ICS_WARN_CHANNEL	"ChannelICSWarn"
#define ICS_AUDIT_DATA_BUF_MAX	256
#define ICS_STUDY_DATA_BUF_MAX	256
#define ICS_WARN_DATA_BUF_MAX	512

typedef enum {
	BEGIN = 1,
	TEMPLATE_ID,
	SRC_MAC,
	DST_MAC,
	SRC_IPv4,
	DST_IPv4,
	SRC_PORT,
	DST_PORT,
	PROTO,
	FLOW_HASH,
	PKTLEN,
	PAYLOAD_LEN,
	APP_PROTO,
	MODBUS_AUDIT_DATA,
	MODBUS_STUDY_DATA,
	MODBUS_WARNING_DATA,
	DNP3_FUNCODE,
	DNP3_OBJECT_COUNTS,
	DNP3_OBJECTS,
	DNP3_WARNING_DATA,
	TRDP_AUDIT_DATA,
	TRDP_STUDY_DATA,
	TRDP_WARNING_DATA,
	END,
} ics_tlv_type_t;

void ICSRedisLogRegister(void);
#endif
